# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitbak < Formula
  desc "Get your dotfiles/config files backed up and managed with Git."
  homepage ""
  version "1.3.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/kennyparsons/gitbak/releases/download/v1.3.2/gitbak_Darwin_x86_64.tar.gz"
    sha256 "80fc71ba9994743db5863c86b2a54b13b55509edbd92ea7a12fd3bb8f8925cbc"

    define_method(:install) do
      bin.install "gitbak"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/kennyparsons/gitbak/releases/download/v1.3.2/gitbak_Darwin_arm64.tar.gz"
    sha256 "b48ee03fbb2f8f6206418e1ea61058388c8f0c79da859be85d04af5832adb20f"

    define_method(:install) do
      bin.install "gitbak"
    end
  end

  test do
    system "#{bin}/gitbak --version"
  end
end
